# Generated by Django 3.0.5 on 2020-05-04 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0003_auto_20191018_2326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='vote',
        ),
    ]
