# Generated by Django 3.0.3 on 2020-02-12 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidates', '0003_auto_20191018_2326'),
    ]

    operations = [
        migrations.CreateModel(
            name='election',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('candidates', models.ManyToManyField(to='candidates.candidate')),
            ],
        ),
    ]
